import { Geist, Geist_Mono } from "next/font/google";
import { Paytone_One } from "next/font/google";
import "./globals.css";

const paytone = Paytone_One({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "P2vest Technology Limited",
  ketwords: "online-banking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${paytone.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
